#!/usr/bin/env python3
"""Regenerate mozilla-roots.pem from NSS certdata.txt.

    gen-roots.py <certdata.txt> <nss-version> > mozilla-roots.pem

Keeps exactly the roots Mozilla trusts to issue TLS server certificates
(CKA_TRUST_SERVER_AUTH = CKT_NSS_TRUSTED_DELEGATOR) and drops every root that
carries a CKA_NSS_SERVER_DISTRUST_AFTER date (on the certificate or on its
trust object — NSS has used both): a PEM bundle cannot express
"trusted only for certificates issued before", so such a root would be
trusted unconditionally. Output is deterministic (certdata order).
"""
import base64
import sys


def parse(path):
    objs, cur, key, octal = [], None, None, None
    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n")
        if octal is not None:
            if line == "END":
                cur[key] = bytes(octal)
                octal = None
            else:
                for tok in line.split("\\")[1:]:
                    octal.append(int(tok, 8))
            continue
        if not line or line.startswith("#"):
            continue
        parts = line.split(" ", 2)
        if parts[0] == "CKA_CLASS":
            cur = {}
            objs.append(cur)
        if cur is None or len(parts) < 2:
            continue
        name, typ = parts[0], parts[1]
        if typ == "MULTILINE_OCTAL":
            key, octal = name, []
        else:
            cur[name] = parts[2] if len(parts) > 2 else typ
            if typ in ("CK_OBJECT_CLASS", "CK_TRUST", "CK_BBOOL"):
                cur[name] = parts[2]
    return objs


def main():
    certdata, version = sys.argv[1], sys.argv[2]
    objs = parse(certdata)
    trust = {}
    for o in objs:
        if o.get("CKA_CLASS") == "CKO_NSS_TRUST":
            trust[(o["CKA_ISSUER"], o["CKA_SERIAL_NUMBER"])] = o
    kept, dropped = [], []
    for o in objs:
        if o.get("CKA_CLASS") != "CKO_CERTIFICATE":
            continue
        label = o["CKA_LABEL"].strip('"')
        t = trust.get((o["CKA_ISSUER"], o["CKA_SERIAL_NUMBER"]), {})
        if t.get("CKA_TRUST_SERVER_AUTH") != "CKT_NSS_TRUSTED_DELEGATOR":
            continue
        if any(isinstance(x.get("CKA_NSS_SERVER_DISTRUST_AFTER"), bytes) for x in (o, t)):
            dropped.append(label)
            continue
        kept.append((label, o["CKA_VALUE"]))
    out = sys.stdout
    out.write("# Mozilla NSS %s TLS server-auth roots, %d certificates.\n" % (version, len(kept)))
    out.write("# Generated by gen-roots.py; roots with a server distrust-after date are\n")
    out.write("# omitted (%s).\n" % ", ".join(dropped))
    for label, der in kept:
        b64 = base64.b64encode(der).decode()
        out.write("\n# %s\n-----BEGIN CERTIFICATE-----\n" % label)
        for i in range(0, len(b64), 64):
            out.write(b64[i:i + 64] + "\n")
        out.write("-----END CERTIFICATE-----\n")


main()
