#!/usr/bin/env python3
"""Regenerate mozilla-roots.pem from NSS certdata.txt.

    gen-roots.py <certdata.txt> <nss-version> > mozilla-roots.pem

Keeps exactly the roots Mozilla trusts to issue TLS server certificates
(CKA_TRUST_SERVER_AUTH = CKT_NSS_TRUSTED_DELEGATOR) and drops every root that
carries a CKA_NSS_SERVER_DISTRUST_AFTER date (on the certificate or on its
trust object — NSS has used both): a PEM bundle cannot express
"trusted only for certificates issued before", so such a root would be
trusted unconditionally. Roots already expired on the day this runs are
dropped too. Output is deterministic (certdata order) for a given day.
"""
import base64
import datetime
import sys


def der_tlv(buf, pos):
    tag, n = buf[pos], buf[pos + 1]
    pos += 2
    if n & 0x80:
        k = n & 0x7F
        n = int.from_bytes(buf[pos:pos + k], "big")
        pos += k
    return tag, pos, pos + n


def not_after(der):
    """notAfter of an X.509 certificate, from its DER."""
    _, pos, _ = der_tlv(der, 0)          # Certificate
    _, pos, _ = der_tlv(der, pos)        # TBSCertificate
    if der[pos] == 0xA0:                 # [0] version
        pos = der_tlv(der, pos)[2]
    for _ in range(3):                   # serialNumber, signature, issuer
        pos = der_tlv(der, pos)[2]
    _, pos, _ = der_tlv(der, pos)        # validity
    pos = der_tlv(der, pos)[2]           # notBefore
    tag, start, end = der_tlv(der, pos)
    text = der[start:end].decode()
    fmt = "%y%m%d%H%M%SZ" if tag == 0x17 else "%Y%m%d%H%M%SZ"
    return datetime.datetime.strptime(text, fmt).replace(tzinfo=datetime.timezone.utc)


def parse(path):
    objs, cur, key, octal = [], None, None, None
    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n")
        if octal is not None:
            if line == "END":
                cur[key] = bytes(octal)
                octal = None
            else:
                for tok in line.split("\\")[1:]:
                    octal.append(int(tok, 8))
            continue
        if not line or line.startswith("#"):
            continue
        parts = line.split(" ", 2)
        if parts[0] == "CKA_CLASS":
            cur = {}
            objs.append(cur)
        if cur is None or len(parts) < 2:
            continue
        name, typ = parts[0], parts[1]
        if typ == "MULTILINE_OCTAL":
            key, octal = name, []
        else:
            cur[name] = parts[2] if len(parts) > 2 else typ
            if typ in ("CK_OBJECT_CLASS", "CK_TRUST", "CK_BBOOL"):
                cur[name] = parts[2]
    return objs


def main():
    certdata, version = sys.argv[1], sys.argv[2]
    objs = parse(certdata)
    trust = {}
    for o in objs:
        if o.get("CKA_CLASS") == "CKO_NSS_TRUST":
            trust[(o["CKA_ISSUER"], o["CKA_SERIAL_NUMBER"])] = o
    now = datetime.datetime.now(datetime.timezone.utc)
    kept, dropped, expired = [], [], []
    for o in objs:
        if o.get("CKA_CLASS") != "CKO_CERTIFICATE":
            continue
        label = o["CKA_LABEL"].strip('"')
        t = trust.get((o["CKA_ISSUER"], o["CKA_SERIAL_NUMBER"]), {})
        if t.get("CKA_TRUST_SERVER_AUTH") != "CKT_NSS_TRUSTED_DELEGATOR":
            continue
        if any(isinstance(x.get("CKA_NSS_SERVER_DISTRUST_AFTER"), bytes) for x in (o, t)):
            dropped.append(label)
            continue
        if not_after(o["CKA_VALUE"]) <= now:
            expired.append(label)
            continue
        kept.append((label, o["CKA_VALUE"]))
    out = sys.stdout
    out.write("# Mozilla NSS %s TLS server-auth roots, %d certificates.\n" % (version, len(kept)))
    out.write("# Generated by gen-roots.py; roots with a server distrust-after date are\n")
    out.write("# omitted (%s).\n" % ", ".join(dropped))
    if expired:
        out.write("# Expired on %s, also omitted: %s.\n" % (now.date(), ", ".join(expired)))
    for label, der in kept:
        b64 = base64.b64encode(der).decode()
        out.write("\n# %s\n-----BEGIN CERTIFICATE-----\n" % label)
        for i in range(0, len(b64), 64):
            out.write(b64[i:i + 64] + "\n")
        out.write("-----END CERTIFICATE-----\n")


main()
